---
title: "0_Feature_Selection_Correlations"
author: "Ryan Wallis"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("gplots") 
library("RColorBrewer")
library("matrixStats")
library("plyr")
library("dplyr")
library("data.table")
library("stringr")
library("ggplot2")
library("Rtsne")



#Import siGlo Control ST Data
All_ST_Clean <- read.csv("All_ST_Clean.csv") # Note this takes a long time to run

#Remove Final Low Quality Measures
numdata <- All_ST_Clean [,-c(1,2,17,18,19,21,56,57,60)]
numdatadf <- data.frame(numdata)
sapply(numdatadf,is.numeric)


#Generate Correlation Matrix 

library(corrplot)
col <- colorRampPalette(c( "#77AADD", "#4477AA", "#FFFFFF", "#EE9988","#BB4444" ))
df_cor <- cor(numdatadf, use=c("pairwise.complete.obs")) # This will also take some time to run 
#makes labels fit in margins
par(xpd=TRUE)
corrplot(df_cor, method="color", col=col(20),  
         type="full", order="hclust", tl.cex = 0.01, # Add coefficient of correlation
         tl.col="black", tl.srt=90, #Text label color and rotation
         # hide correlation coefficient on the principal diagonal
         diag=T,mar = c(2, 0, 1, 0))


#Generate Correlation Tables
library("caret")
High_corr <- findCorrelation(df_cor, cutoff = .9, verbose = TRUE, names = TRUE)
hc = findCorrelation(df_cor, cutoff=0.9) # putt any value as a "cutoff" 
hc = sort(hc)
reduced_Data = df_cor[,-c(hc)]
reduced_Data <- as.data.frame(reduced_Data)

#Full Correlation Matrix
write.csv(df_cor, "Correlation Matrix.csv")
#Retained Features Matrix - Columns 
write.csv(reduced_Data, "Reduced Data.csv")
#Removed Features
write.csv(High_corr, "Correlated Measures.csv")


```

